services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
  
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  todo-backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    #ports:
    #  - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017/todos

volumes:
  redis_data: